spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db
    username: user_service
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: myVerySecretKeyForJWTTokenGenerationThatShouldBeLongEnough
  expiration: 86400000

logging:
  level:
    com.movietix.user: DEBUG
    org.springframework.security: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-user:3306/user_service_db
    username: user_service
    password: userpassword

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/